### ISSUE TITLE
Brilliant work-in-progress logo

### ISSUE THREAD

**Issue by distantnative** [kirby-kart/kart#10]
:stuck_out_tongue_winking_eye: 

![kart](https://cloud.githubusercontent.com/assets/3788865/6518785/37c990b4-c3ab-11e4-8f8b-4d481ffb93bf.jpg)

**Comment by plaidscreen** [comment]
Amazing.

**Comment by benseitz** [comment]
Perfect

**Comment by distantnative** [comment]
Can our organization have this as a logo until we get an actual one? :D

**Comment by plaidscreen** [comment]
I just added it, but sometimes it takes awhile for Github's cache to update.

**Comment by distantnative** [comment]
:+1:
