### ISSUE TITLE
Event hooks / triggers & content filters

### ISSUE THREAD

**Issue by plaidscreen** [kirby-kart/kart#4]
Wordpress calls them actions and filters, I want to do something similar inside Kart. But it wouldn't necessarily need to be part of the Kart core, it could just be a separate plugin with a set of classes that Kart requires. I would use the plugin on all sorts of other projects.

I also don't want to reinvent the wheel. If Kirby 2.1 is bringing its own event hooks for the Panel, surely those classes will be available for plugin developers to implement. So maybe we'll have to write our own hook system for the interim, and when Kirby comes out with a standard, we'll rewrite the plugin as a wrapper for Kirby's classes, and then slowly deprecate its usage.

So anyway, I envision usage like:

```PHP
Event::on("hook name", function($arg1, $arg2) 
{
  //do some stuff
  return $something; //return value is optional, used for content filters
});
Event::trigger("hook name", $local_variable, $another_variable);
```

Or if you need to use it as a filter:

```PHP
$local_variable = Event::filter("hook name", $local_variable, $another_variable);
```

Thoughts?

**Comment by distantnative** [comment]
I could imagine that something like this should be part of the core. Even if we don't need it in the core itself, if quite a few Kart plugins rely on this, it would create all these dependencies: if you want to add this plugin you also have to add this plugin.

So I'd see the core also as a provider for the basic tools that plugins will use. So that not every plugin has to bring their own.

**Comment by benseitz** [comment]
I agree with @distantnative

**Comment by plaidscreen** [comment]
I'm interested in at least making it a separate repository (and a sub-repo dependency of Kart) so that I can use it on non-Kart projects. How do you feel about that?

**Comment by distantnative** [comment]
:+1:

**Comment by benseitz** [comment]
:+1:
