### ISSUE TITLE
Plugins/addons... what do we call it?

### ISSUE THREAD

**Issue by distantnative** [kirby-kart/kart#7]
Just to not bloat one issue up with even mores (even if its just as small as this one):
@benseitz has a valid point, that we might not wanna call Kart's optional packages "plugins", cause that's what Kirby has and Kart is a plugin itself. So what do we call them? Addons?

I'd vote for "modules" – fits much better to things as tax, shipping etc. in my opinion

**Comment by benseitz** [comment]
Modules is already taken by kirby: https://vimeo.com/115805751
We've got plugins, snippets, widgets, ... so i vote for addons

**Comment by distantnative** [comment]
Ah true. I wouldn't hate addons, so :wink: What do you think, @plaidscreen ?

**Comment by plaidscreen** [comment]
Yeah... plugins makes me think it's a Kirby plugin
modules makes me think it's a Git submodule
I think we'll have to go with addons by process of elimination. I don't love addons, but I don't hate it. :)

**Comment by benseitz** [comment]
So do I ;)

**Comment by benseitz** [comment]
Or we could name them kart wheels :D 
But that would overcomplicate things

**Comment by distantnative** [comment]
Haha yea. Let's stick with addons for the moment. If someone has a brilliant naming idea along the way, we can still bring it up again.

**Comment by plaidscreen** [comment]
I just thought of another name, "extensions"
So - addons or extensions - which do both of you like better? I have an opinion, but I'll be the swing vote if needed.

**Comment by distantnative** [comment]
I'd like extensions better than addons

**Comment by benseitz** [comment]
"extensions" may be the better description, but "addons" is shorter and catchier... but I really wouldn't mind "extensions", so it's up to you @plaidscreen

**Comment by plaidscreen** [comment]
I like extensions better. So I guess I'll change the repo. :smile:
