### ISSUE TITLE
product management

### ISSUE THREAD

**Issue by benseitz** [kirby-kart/kart#8]
There more I think about it: product management is the center of a shop: taxes, stock, price, options...
Changing these things in the standard kirby content structure seems complicated?
How about a separate list with all products and just link them with their ID in a blueprint?

**Comment by distantnative** [comment]
What do you mean with separate list?

**Comment by benseitz** [comment]
Besides the content structure - like user accounts

**Comment by distantnative** [comment]
But then you would still set up a normal page for each product and just refer the ProductID?

**Comment by benseitz** [comment]
But there could be some batch processing - changing all taxes at once or make all jeans 10% cheaper.

**Comment by plaidscreen** [comment]
> But there could be some batch processing - changing all taxes at once or make all jeans 10% cheaper.

You could still accomplish this with blueprints. A panel function could go do math on all products that are assigned to a certain category, tag, or parent.

It's my preference that we keep Products as standard kirby content. In the panel, I thought it might make sense if a little alert showed up at the top of the page saying "You don't have a Product blueprint setup [Click here] to create one" - and then it'd automatically generated the base product blueprint.

**Comment by distantnative** [comment]
And taxes or similar could be assigned as a tag to a product, e.g. this gets the reduced VAT. So if something changes to the reduced VAT, you edit this for the tax info and it immediately works for all tagged products. And only if a product needs to move to a different tax category, you have to edit the product and change the tax tag.

**Comment by benseitz** [comment]
okay :+1:
